.TH "AutoWave_class.str_and_req" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.str_and_req
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprefix\fP)"
.br
.ti -1c
.RI "def \fBstr\fP (self)"
.br
.ti -1c
.RI "def \fBreq\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBcmd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB363\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.str_and_req\&.__init__ ( self,  prefix)"

.PP
Definition at line \fB364\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def AutoWave_class\&.str_and_req\&.req ( self)"

.PP
Definition at line \fB371\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "def AutoWave_class\&.str_and_req\&.str ( self)"

.PP
Definition at line \fB368\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.str_and_req\&.cmd"

.PP
Definition at line \fB366\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.str_and_req\&.prefix"

.PP
Definition at line \fB365\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
