.TH "AutoWave_class.storage" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.storage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmd\fP"
.br
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBidn\fP"
.br
.ti -1c
.RI "\fBreset\fP"
.br
.ti -1c
.RI "\fBgo_to_local\fP"
.br
.ti -1c
.RI "\fBecho\fP"
.br
.ti -1c
.RI "\fBreboot\fP"
.br
.ti -1c
.RI "\fBprotocol\fP"
.br
.ti -1c
.RI "\fBstatus\fP"
.br
.ti -1c
.RI "\fBstop_test\fP"
.br
.ti -1c
.RI "\fBstart_test\fP"
.br
.ti -1c
.RI "\fBbreak_test\fP"
.br
.ti -1c
.RI "\fBmode\fP"
.br
.ti -1c
.RI "\fBsetVoltage\fP"
.br
.ti -1c
.RI "\fBsetOffset\fP"
.br
.ti -1c
.RI "\fBdisplay\fP"
.br
.ti -1c
.RI "\fBset_date\fP"
.br
.ti -1c
.RI "\fBreq_date\fP"
.br
.ti -1c
.RI "\fBfile\fP"
.br
.ti -1c
.RI "\fBtrigGen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB419\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.storage\&.__init__ ( self)"

.PP
Definition at line \fB420\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.storage\&.break_test"

.PP
Definition at line \fB432\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.cmd"

.PP
Definition at line \fB421\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.display"

.PP
Definition at line \fB436\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.echo"

.PP
Definition at line \fB426\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.file"

.PP
Definition at line \fB439\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.go_to_local"

.PP
Definition at line \fB425\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.idn"

.PP
Definition at line \fB423\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.mode"

.PP
Definition at line \fB433\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.prefix"

.PP
Definition at line \fB422\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.protocol"

.PP
Definition at line \fB428\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.reboot"

.PP
Definition at line \fB427\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.req_date"

.PP
Definition at line \fB438\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.reset"

.PP
Definition at line \fB424\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.set_date"

.PP
Definition at line \fB437\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.setOffset"

.PP
Definition at line \fB435\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.setVoltage"

.PP
Definition at line \fB434\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.start_test"

.PP
Definition at line \fB431\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.status"

.PP
Definition at line \fB429\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.stop_test"

.PP
Definition at line \fB430\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.storage\&.trigGen"

.PP
Definition at line \fB440\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
