.TH "AutoWave_class.trig_gen" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.trig_gen
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprefix\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBcmd\fP"
.br
.ti -1c
.RI "\fBoff\fP"
.br
.ti -1c
.RI "\fBmanual_start\fP"
.br
.ti -1c
.RI "\fBtrigIn_start\fP"
.br
.ti -1c
.RI "\fBauto\fP"
.br
.ti -1c
.RI "\fBmanual_event\fP"
.br
.ti -1c
.RI "\fBtrigIn_event\fP"
.br
.ti -1c
.RI "\fBmanual_iter\fP"
.br
.ti -1c
.RI "\fBtrigIn_iter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB490\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.trig_gen\&.__init__ ( self,  prefix)"

.PP
Definition at line \fB491\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.trig_gen\&.auto"

.PP
Definition at line \fB497\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.cmd"

.PP
Definition at line \fB493\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.manual_event"

.PP
Definition at line \fB498\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.manual_iter"

.PP
Definition at line \fB500\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.manual_start"

.PP
Definition at line \fB495\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.off"

.PP
Definition at line \fB494\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.prefix"

.PP
Definition at line \fB492\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.trigIn_event"

.PP
Definition at line \fB499\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.trigIn_iter"

.PP
Definition at line \fB501\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.trig_gen\&.trigIn_start"

.PP
Definition at line \fB496\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
