.TH "AutoWave_class.set_voltage" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.set_voltage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprefix\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBcmd\fP"
.br
.ti -1c
.RI "\fBout1\fP"
.br
.ti -1c
.RI "\fBout2\fP"
.br
.ti -1c
.RI "\fBout3\fP"
.br
.ti -1c
.RI "\fBout4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB486\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.set_voltage\&.__init__ ( self,  prefix)"

.PP
Definition at line \fB487\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.set_voltage\&.cmd"

.PP
Definition at line \fB489\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.set_voltage\&.out1"

.PP
Definition at line \fB491\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.set_voltage\&.out2"

.PP
Definition at line \fB492\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.set_voltage\&.out3"

.PP
Definition at line \fB493\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.set_voltage\&.out4"

.PP
Definition at line \fB494\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.set_voltage\&.prefix"

.PP
Definition at line \fB488\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
