.TH "C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src/Autowave_class_test.py" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src/Autowave_class_test.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAutowave_class_test\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAutowave_class_test\&.timer\fP = \fBTimer_class\&.Timer\fP()"
.br
.ti -1c
.RI "string \fBAutowave_class_test\&.inst_folder\fP = '/home/guest/DowFiles'"
.br
.ti -1c
.RI "list \fBAutowave_class_test\&.WaveFormA\fP"
.br
.ti -1c
.RI "\fBAutowave_class_test\&.inst\fP = \fBAutoWave_class\&.com_interface\fP()"
.br
.ti -1c
.RI "\fBAutowave_class_test\&.test_time\fP = inst\&.get_test_time(test)"
.br
.ti -1c
.RI "\fBAutowave_class_test\&.test_status\fP = inst\&.check_test_status()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
