.TH "AutoWave_class.file" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.file
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprefix\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBcmd\fP"
.br
.ti -1c
.RI "\fBdelete\fP"
.br
.ti -1c
.RI "\fBget_file_list\fP"
.br
.ti -1c
.RI "\fBget_dir_download\fP"
.br
.ti -1c
.RI "\fBget_dir_record\fP"
.br
.ti -1c
.RI "\fBget_dir_upgrade\fP"
.br
.ti -1c
.RI "\fBget_file_size\fP"
.br
.ti -1c
.RI "\fBTRLF\fP"
.br
.ti -1c
.RI "\fBTRLF_req\fP"
.br
.ti -1c
.RI "\fBcheck_file_exist\fP"
.br
.ti -1c
.RI "\fBcheck_details\fP"
.br
.ti -1c
.RI "\fBcheck_total_duration\fP"
.br
.ti -1c
.RI "\fBselect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB478\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.file\&.__init__ ( self,  prefix)"

.PP
Definition at line \fB490\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.file\&.check_details"

.PP
Definition at line \fB503\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.check_file_exist"

.PP
Definition at line \fB502\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.check_total_duration"

.PP
Definition at line \fB504\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.cmd"

.PP
Definition at line \fB492\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.delete"

.PP
Definition at line \fB493\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.get_dir_download"

.PP
Definition at line \fB495\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.get_dir_record"

.PP
Definition at line \fB496\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.get_dir_upgrade"

.PP
Definition at line \fB497\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.get_file_list"

.PP
Definition at line \fB494\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.get_file_size"

.PP
Definition at line \fB499\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.prefix"

.PP
Definition at line \fB491\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.select"

.PP
Definition at line \fB505\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.TRLF"

.PP
Definition at line \fB500\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.file\&.TRLF_req"

.PP
Definition at line \fB501\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
