.TH "AutoWave_class.dig_param3" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.dig_param3
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprefix\fP, \fBmin\fP, \fBmax\fP)"
.br
.ti -1c
.RI "def \fBval\fP (self, count=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBcmd\fP"
.br
.ti -1c
.RI "\fBmax\fP"
.br
.ti -1c
.RI "\fBmin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB415\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.dig_param3\&.__init__ ( self,  prefix,  min,  max)"

.PP
Definition at line \fB416\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def AutoWave_class\&.dig_param3\&.val ( self,  count = \fC0\fP)"

.PP
Definition at line \fB422\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.dig_param3\&.cmd"

.PP
Definition at line \fB418\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.dig_param3\&.max"

.PP
Definition at line \fB419\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.dig_param3\&.min"

.PP
Definition at line \fB420\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.dig_param3\&.prefix"

.PP
Definition at line \fB417\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
