.TH "AutoWave_class.str3" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.str3
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprefix\fP)"
.br
.ti -1c
.RI "def \fBstr\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBcmd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB354\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.str3\&.__init__ ( self,  prefix)"

.PP
Definition at line \fB355\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def AutoWave_class\&.str3\&.str ( self)"

.PP
Definition at line \fB359\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.str3\&.cmd"

.PP
Definition at line \fB357\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.str3\&.prefix"

.PP
Definition at line \fB356\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
