.TH "C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src/AutoWave_class.py" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src/AutoWave_class.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutoWave_class\&.com_interface\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.req3\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.str3\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.str_and_req\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.req_on_off\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.dig_param\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.dig_param3\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.str_param3\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.storage\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.mode\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.trig_gen\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.set_voltage\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.file\fP"
.br
.ti -1c
.RI "class \fBAutoWave_class\&.status\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAutoWave_class\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBAutoWave_class\&.delay\fP (time_in_sec=0\&.25)"
.br
.ti -1c
.RI "def \fBAutoWave_class\&.range_check\fP (val, min, max, val_name)"
.br
.ti -1c
.RI "def \fBAutoWave_class\&.str2dec_array\fP (txt)"
.br
.ti -1c
.RI "def \fBAutoWave_class\&.dec_array2check_sum\fP (dec_array)"
.br
.ti -1c
.RI "def \fBAutoWave_class\&.str2check_sum\fP (txt)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAutoWave_class\&.cmd\fP = storage()"
.br
.ti -1c
.RI "list \fBAutoWave_class\&.cmd_list\fP = []"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
