.TH "Autowave_class_test" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Autowave_class_test
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtimer\fP = \fBTimer_class\&.Timer\fP()"
.br
.ti -1c
.RI "string \fBinst_folder\fP = '/home/guest/DowFiles'"
.br
.ti -1c
.RI "list \fBWaveFormA\fP"
.br
.ti -1c
.RI "\fBinst\fP = \fBAutoWave_class\&.com_interface\fP()"
.br
.ti -1c
.RI "\fBtest_time\fP = inst\&.get_test_time(test)"
.br
.ti -1c
.RI "\fBtest_status\fP = inst\&.check_test_status()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Autowave_class_test\&.inst = \fBAutoWave_class\&.com_interface\fP()"

.PP
Definition at line \fB29\fP of file \fBAutowave_class_test\&.py\fP\&.
.SS "string Autowave_class_test\&.inst_folder = '/home/guest/DowFiles'"

.PP
Definition at line \fB10\fP of file \fBAutowave_class_test\&.py\fP\&.
.SS "Autowave_class_test\&.test_status = inst\&.check_test_status()"

.PP
Definition at line \fB45\fP of file \fBAutowave_class_test\&.py\fP\&.
.SS "Autowave_class_test\&.test_time = inst\&.get_test_time(test)"

.PP
Definition at line \fB35\fP of file \fBAutowave_class_test\&.py\fP\&.
.SS "Autowave_class_test\&.timer = \fBTimer_class\&.Timer\fP()"

.PP
Definition at line \fB5\fP of file \fBAutowave_class_test\&.py\fP\&.
.SS "list Autowave_class_test\&.WaveFormA"
\fBInitial value:\fP
.PP
.nf
1 =  [
2             "JLC_CI256_WFA_20000ms\&.dpt",
3             "JLR_CI265_WFA_1000ms\&.dpt",
4             "JLR_CI265_WFA_200ms\&.dpt",
5             "JLR_CI265_WFA_100ms\&.dpt",
6             "JLR_CI265_WFA_60ms\&.dpt",
7             "JLR_CI265_WFA_48ms\&.dpt",
8             "JLR_CI265_WFA_35ms\&.dpt",
9             "JLR_CI265_WFA_24ms\&.dpt",
10             "JLR_CI265_WFA_18ms\&.dpt",
11             "JLR_CI265_WFA_12ms\&.dpt",
12             "JLR_CI265_WFA_9ms\&.dpt",
13             "JLR_CI265_WFA_6ms\&.dpt",
14             "JLR_CI265_WFA_3ms\&.dpt",
15 ]
.fi
.PP
Definition at line \fB12\fP of file \fBAutowave_class_test\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
