.TH "AutoWave_class.req3" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.req3
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAutoWave_class\&.mode\fP, and \fBAutoWave_class\&.req_on_off\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBprefix\fP)"
.br
.ti -1c
.RI "def \fBreq\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBcmd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB382\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.req3\&.__init__ ( self,  prefix)"

.PP
Reimplemented in \fBAutoWave_class\&.req_on_off\fP, and \fBAutoWave_class\&.mode\fP\&.
.PP
Definition at line \fB383\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def AutoWave_class\&.req3\&.req ( self)"

.PP
Definition at line \fB387\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.req3\&.cmd"

.PP
Definition at line \fB385\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.req3\&.prefix"

.PP
Definition at line \fB384\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
