.TH "AutoWave_class.status" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.status
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmd\fP"
.br
.ti -1c
.RI "\fBprefix\fP"
.br
.ti -1c
.RI "\fBsys_ver\fP"
.br
.ti -1c
.RI "\fBread_mac\fP"
.br
.ti -1c
.RI "\fBread_out1_status\fP"
.br
.ti -1c
.RI "\fBread_out2_status\fP"
.br
.ti -1c
.RI "\fBread_out3_status\fP"
.br
.ti -1c
.RI "\fBread_out4_status\fP"
.br
.ti -1c
.RI "\fBread_in1_status\fP"
.br
.ti -1c
.RI "\fBread_in2_status\fP"
.br
.ti -1c
.RI "\fBread_test_status\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB508\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.status\&.__init__ ( self)"

.PP
Definition at line \fB509\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.status\&.cmd"

.PP
Definition at line \fB511\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.prefix"

.PP
Definition at line \fB512\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_in1_status"

.PP
Definition at line \fB519\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_in2_status"

.PP
Definition at line \fB520\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_mac"

.PP
Definition at line \fB514\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_out1_status"

.PP
Definition at line \fB515\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_out2_status"

.PP
Definition at line \fB516\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_out3_status"

.PP
Definition at line \fB517\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_out4_status"

.PP
Definition at line \fB518\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.read_test_status"

.PP
Definition at line \fB521\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.status\&.sys_ver"

.PP
Definition at line \fB513\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
