.TH "AutoWave_class.dig_param" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoWave_class.dig_param
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBval\fP (self, count=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmd\fP"
.br
.ti -1c
.RI "\fBmax\fP"
.br
.ti -1c
.RI "\fBmin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB384\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def AutoWave_class\&.dig_param\&.__init__ ( self)"

.PP
Definition at line \fB385\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def AutoWave_class\&.dig_param\&.val ( self,  count = \fC0\fP)"

.PP
Definition at line \fB390\fP of file \fBAutoWave_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AutoWave_class\&.dig_param\&.cmd"

.PP
Definition at line \fB386\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.dig_param\&.max"

.PP
Definition at line \fB387\fP of file \fBAutoWave_class\&.py\fP\&.
.SS "AutoWave_class\&.dig_param\&.min"

.PP
Definition at line \fB388\fP of file \fBAutoWave_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
