.TH "C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src Directory Reference" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAutoWave_class\&.py\fP"
.br
.ti -1c
.RI "file \fBAutowave_class_test\&.py\fP"
.br
.ti -1c
.RI "file \fBGPIB_pyvisa\&.py\fP"
.br
.ti -1c
.RI "file \fBProtocol_check\&.py\fP"
.br
.ti -1c
.RI "file \fBTimer_class\&.py\fP"
.br
.in -1c
