.TH "Protocol_check" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protocol_check
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBinputString\fP = 'STAT? PSRC'"
.br
.ti -1c
.RI "int \fBsum\fP = 0"
.br
.ti -1c
.RI "list \fBcmd\fP = []"
.br
.ti -1c
.RI "int \fBcheck_sum\fP = \fBsum\fP & 0x00FF"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int Protocol_check\&.check_sum = \fBsum\fP & 0x00FF"

.PP
Definition at line \fB16\fP of file \fBProtocol_check\&.py\fP\&.
.SS "list Protocol_check\&.cmd = []"

.PP
Definition at line \fB8\fP of file \fBProtocol_check\&.py\fP\&.
.SS "string Protocol_check\&.inputString = 'STAT? PSRC'"

.PP
Definition at line \fB2\fP of file \fBProtocol_check\&.py\fP\&.
.SS "int Protocol_check\&.sum = 0"

.PP
Definition at line \fB6\fP of file \fBProtocol_check\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
