.TH "C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src/Protocol_check.py" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/alexandr/PycharmProjects/Libs/AutoWave/src/Protocol_check.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProtocol_check\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBProtocol_check\&.inputString\fP = 'STAT? PSRC'"
.br
.ti -1c
.RI "int \fBProtocol_check\&.sum\fP = 0"
.br
.ti -1c
.RI "list \fBProtocol_check\&.cmd\fP = []"
.br
.ti -1c
.RI "int \fBProtocol_check\&.check_sum\fP = sum & 0x00FF"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
