.TH "Timer_class.TimerError" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer_class.TimerError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
A custom exception used to report errors in use of Timer class
.fi
.PP
 
.PP
Definition at line \fB3\fP of file \fBTimer_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
