.TH "Timer_class.Timer" 3 "Tue Oct 5 2021" "AutoWave control python library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer_class.Timer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBstart\fP (self, time_in_sec)"
.br
.ti -1c
.RI "def \fBget_time\fP (self)"
.br
.ti -1c
.RI "def \fBis_finihed\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_start_time\fP"
.br
.ti -1c
.RI "\fB_target_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTimer_class\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Timer_class\&.Timer\&.__init__ ( self)"

.PP
Definition at line \fB7\fP of file \fBTimer_class\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def Timer_class\&.Timer\&.get_time ( self)"

.PP
Definition at line \fB18\fP of file \fBTimer_class\&.py\fP\&.
.SS "def Timer_class\&.Timer\&.is_finihed ( self)"

.PP
Definition at line \fB26\fP of file \fBTimer_class\&.py\fP\&.
.SS "def Timer_class\&.Timer\&.start ( self,  time_in_sec)"

.PP
Definition at line \fB11\fP of file \fBTimer_class\&.py\fP\&.
.SS "def Timer_class\&.Timer\&.stop ( self)"

.PP
.nf
Stop the timer, and report the elapsed time
.fi
.PP
 
.PP
Definition at line \fB37\fP of file \fBTimer_class\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Timer_class\&.Timer\&._start_time\fC [private]\fP"

.PP
Definition at line \fB8\fP of file \fBTimer_class\&.py\fP\&.
.SS "Timer_class\&.Timer\&._target_time\fC [private]\fP"

.PP
Definition at line \fB9\fP of file \fBTimer_class\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AutoWave control python library from the source code\&.
